<a href="https://colab.research.google.com/github/SudhanshuDubey5001/PythonTut/blob/main/Python_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Everything in Python is an object (an instance of a class).
To know the type of the object -

In [ ]:
type(1000)

int

Take help using help function

In [ ]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |
 |  Built-in subclasses:
 |      bool
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __ceil__(...)
 |      Ceiling of an Integral returns itself.
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floor__(...)
 |      Flooring an Integral returns itself.
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(self, format_spec, /)
 |      Default object formatter.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __index__(self, /)
 |      Return self converted to an integer, if self is suitable for use as an index into a list.
 |
 |  __int__(self, /)
 |      int(self)
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lshift__(self, value, /)
 |      Return self<<value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __neg__(self, /)
 |      -self
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __pos__(self, /)
 |      +self
 |
 |  __pow__(self, value, mod=None, /)
 |      Return pow(self, value, mod).
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __rdivmod__(self, value, /)
 |      Return divmod(value, self).
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rfloordiv__(self, value, /)
 |      Return value//self.
 |
 |  __rlshift__(self, value, /)
 |      Return value<<self.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __round__(...)
 |      Rounding an Integral returns itself.
 |
 |      Rounding with an ndigits argument also returns an integer.
 |
 |  __rpow__(self, value, mod=None, /)
 |      Return pow(value, self, mod).
 |
 |  __rrshift__(self, value, /)
 |      Return value>>self.
 |
 |  __rshift__(self, value, /)
 |      Return self>>value.
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __sizeof__(self, /)
 |      Returns size in memory, in bytes.
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  __truediv__(self, value, /)
 |      Return self/value.
 |
 |  __trunc__(...)
 |      Truncating an Integral returns itself.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  as_integer_ratio(self, /)
 |      Return integer ratio.
 |
 |      Return a pair of integers, whose ratio is exactly equal to the original int
 |      and with a positive denominator.
 |
 |      >>> (10).as_integer_ratio()
 |      (10, 1)
 |      >>> (-10).as_integer_ratio()
 |      (-10, 1)
 |      >>> (0).as_integer_ratio()
 |      (0, 1)
 |
 |  bit_count(self, /)
 |      Number of ones in the binary representation of the absolute value of self.
 |
 |      Also known as the population count.
 |
 |      >>> bin(13)
 |      '0b1101'
 |      >>> (13).bit_count()
 |      3
 |
 |  bit_length(self, /)
 |      Number of bits necessary to represent self in binary.
 |
 |      >>> bin(37)
 |      '0b100101'
 |      >>> (37).bit_length()
 |      6
 |
 |  conjugate(...)
 |      Returns self, the complex conjugate of any int.
 |
 |  to_bytes(self, /, length, byteorder, *, signed=False)
 |      Return an array of bytes representing an integer.
 |
 |      length
 |        Length of bytes object to use.  An OverflowError is raised if the
 |        integer is not representable with the given number of bytes.
 |      byteorder
 |        The byte order used to represent the integer.  If byteorder is 'big',
 |        the most significant byte is at the beginning of the byte array.  If
 |        byteorder is 'little', the most significant byte is at the end of the
 |        byte array.  To request the native byte order of the host system, use
 |        `sys.byteorder' as the byte order value.
 |      signed
 |        Determines whether two's complement is used to represent the integer.
 |        If signed is False and a negative integer is given, an OverflowError
 |        is raised.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_bytes(bytes, byteorder, *, signed=False) from builtins.type
 |      Return the integer represented by the given array of bytes.
 |
 |      bytes
 |        Holds the array of bytes to convert.  The argument must either
 |        support the buffer protocol or be an iterable object producing bytes.
 |        Bytes and bytearray are examples of built-in objects that support the
 |        buffer protocol.
 |      byteorder
 |        The byte order used to represent the integer.  If byteorder is 'big',
 |        the most significant byte is at the beginning of the byte array.  If
 |        byteorder is 'little', the most significant byte is at the end of the
 |        byte array.  To request the native byte order of the host system, use
 |        `sys.byteorder' as the byte order value.
 |      signed
 |        Indicates whether two's complement is used to represent the integer.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  denominator
 |      the denominator of a rational number in lowest terms
 |
 |  imag
 |      the imaginary part of a complex number
 |
 |  numerator
 |      the numerator of a rational number in lowest terms
 |
 |  real
 |      the real part of a complex number

In [ ]:
job_title = 'Data Analyst'
job_location = 'India'

In [ ]:
#Id function tells you the ID of the object that the variable job_title points to. So that you can check if two objects are same
id(job_title)

139083035955056

In [ ]:
id(job_location) #means job_title and job_location are referencing two different objects as they have different Ids

139083035955184

In [ ]:
my_print_func = print
my_print_func('Sup')  #bcz its pointing to the same object "print" function was doing

Sup

In [ ]:
def formatted_print(title, location):
  return print(f'Job title is {title} and location is {location}')

formatted_print(job_title, job_location)

Job title is Data Analyst and location is India

In [ ]:
class Employee:
  def __init__(self, name, title, location):
    self.name = name
    self.title = title
    self.location = location

  def change_name(self, modified_name):
    self.name = modified_name
    print(self.name)

em = Employee(name='Ron', title=job_title, location=job_location)
em.change_name('John')

John

In [ ]:
#int class or str class has some helping methods we can use like -
a = 100
a.__add__(200)

300

Change type -

In [ ]:
f = 100
type(f)

int

In [ ]:
f = float(f)
type(f)

float

String can be in single or double quotes

In [ ]:
s = 'ello'
print('ello'.lower())
print(s.lower())

ello
ello

self -> its like 'this' in Java. An empty container and whatever object calls that function, that object goes inside that container.

In [ ]:
"Data Analyst".split(sep=' ', maxsplit=1)

['Data', 'Analyst']

In [ ]:
"Data   Analyst".split(sep=' ', maxsplit=1)

['Data', '  Analyst']

In [ ]:
"Data   Analyst".split(sep=' ', maxsplit=3)

['Data', '', '', 'Analyst']

In [ ]:
#magic methods or dunder methods- starts with __ and ends with __
s.__add__(' there mate')
s + ' there mate' # same thing '+' is using __add__

'ello there mate'

In [ ]:
"Boo"*10

'BooBooBooBooBooBooBooBooBooBoo'

f-String: Formatted strings where you can use {} to define variables

In [ ]:
print(f"This is my string = {s}")

This is my string = ello

In [ ]:
numbers = '0123456789'
', '.join(numbers)

'0, 1, 2, 3, 4, 5, 6, 7, 8, 9'

In [ ]:
myList = ['Java', 'Python', 'C++']
','.join(myList)

'Java,Python,C++'

In [ ]:
print(5/2)
print(5//2)

2.5
2

**Order of operations**
1. Parenthesis
2. Exponents
3. Multiplication and division: left to right
4. Addition and Subtraction: left to right

In [ ]:
salary = 20_000 # _ is ignored
x=10
x+=10
print(x)

20

In [ ]:
x**=2 #exponent and assign
print(x)

400

In [ ]:
#Swap shortcut
a = 10
b = 20
a, b = b, a
print(a, b)

20 10

In [ ]:
if(a>b):
  print('Yes')
elif(a==b):
  pass  #if just want nothing to happen and no error to display, just write pass or write ... (epilses)
else:
  print('No')

Yes

Lists -
  - Collection of ordered items
  - Ordered

In [ ]:
my_lists = ['a', 1, 'yoyo', [1,'ss']]
print(my_lists)
my_lists[2]

['a', 1, 'yoyo', [1, 'ss']]

'yoyo'

In [ ]:
my_lists.append('obo')
my_lists.remove('obo')  #first occurence
len(my_lists)

4

In [ ]:
my_lists.pop()  #removes last element
my_lists.pop(2)  #removes like normal remove element

'yoyo'

In [ ]:
my_lists.extend(['b','c', 'd'])
# to print some values
my_lists[0:2] #slicing -> 0 index is included and 2 index is not included

['a', 1]

In [ ]:
print(my_lists)
print(my_lists[::1])  #prints every element bcz step size is 1
print(my_lists[::2])  #prints every second element bcz step is 2

['a', 1, 'b', 'c', 'd']
['a', 1, 'b', 'c', 'd']
['a', 'b', 'd']

In [ ]:
listA = ['a','b']
listB = ['b', 'c']
listC = listA + listB  #listA.extend(listB) is working behind the scenes
print(listC)  #can have duplicate elements

['a', 'b', 'b', 'c']

In [ ]:
#get last items
print(listC[-1]) #last item
print(listC[-2]) #second last item
print(listC[-3:]) #three last items. : means list all the items from third last -3 till last index
print(listC[0:])

c
b
['b', 'b', 'c']
['a', 'b', 'b', 'c']

In [ ]:
#assigning var to each element in list -> unpacking
listC.remove('b')
i, j, k = listC
print(i, j, k)

a b c

In [ ]:
i,*j = listC
print(i, j)

a ['b', 'c']

Dictionary - Key value pair
  - Unordered
  - duplicate values are allowed but keys are not

In [ ]:
my_dict = {'a':1, 'b':2, 'c':3}
my_dict['a']

1

In [ ]:
#update values
my_dict['d'] = 100  #single value
my_dict.update({'e':1000, 'f':2000}) #multiple values
print(my_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 100, 'e': 1000, 'f': 2000}

Sets -> Only unique values
- unordered
- no indexing
- Used for extracting unique values

In [ ]:
my_set = {'a', 'b', 'c'}
my_set.add('d')
my_set.remove('b')
print(my_set)

{'a', 'c', 'd'}

In [ ]:
# convert a list to set and vice versa
c_set = set(listC)
c_set
back_toList = list(c_set)
back_toList

['a', 'c', 'b']

Tuple -> same as list
<p> But they are immutable </p

In [ ]:
my_tuple = ('a','b', 3434, ['c', 'd'])
my_tuple[0]

'a'

In [ ]:
# you can actually create a new tuple and add to the previous one. We are not mpdifying the existing one, but creating a new one
my_tuple = my_tuple + ('e', 'f')
my_tuple

('a', 'b', 3434, ['c', 'd'], 'e', 'f')

Range function

In [ ]:
tuple(range(5))

(0, 1, 2, 3, 4)

In [ ]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
list(range(5, 20, 2)) # 5 to 20 and step size is 2

[5, 7, 9, 11, 13, 15, 17, 19]

and, or, not
<p>&, | , ~(NOT), ^(XOR) <<(left shift), >>(right shift) ----> Bitwise operator</p>

In [ ]:
# in operator
'a' in my_tuple

True

In [ ]:
print('data' in 'data_analyst')
print('data' not in 'data_analyst')

True
False

In [ ]:
# is operator checks whether two objects have same memory location or not
a=1000
b=a
a is b

True

In [ ]:
a=1000
b=1000
a is b

False

In [ ]:
import pandas as pd
jobs = pd.read_csv('linkedin-jobs-usa.csv')
jobs.head()

,title,company,description,onsite_remote,salary,location,criteria,posted_date,link
0,Data Analyst - Recent Graduate,PayPal,"At PayPal (NASDAQ: PYPL), we believe that ever...",onsite,NaN,Buffalo-Niagara Falls Area,"[{'Seniority level': 'Not Applicable'}, {'Empl...",2022-11-22,https://www.linkedin.com/jobs/view/data-analys...
1,Data Analyst - Recent Graduate,PayPal,"At PayPal (NASDAQ: PYPL), we believe that ever...",onsite,NaN,"San Jose, CA","[{'Seniority level': 'Not Applicable'}, {'Empl...",2022-11-22,https://www.linkedin.com/jobs/view/data-analys...
2,Data Analyst,PayPal,"At PayPal (NASDAQ: PYPL), we believe that ever...",onsite,NaN,"Texas, United States","[{'Seniority level': 'Not Applicable'}, {'Empl...",2022-11-17,https://www.linkedin.com/jobs/view/data-analys...
3,Data Analyst,PayPal,"At PayPal (NASDAQ: PYPL), we believe that ever...",onsite,NaN,"Illinois, United States","[{'Seniority level': 'Not Applicable'}, {'Empl...",2022-11-17,https://www.linkedin.com/jobs/view/data-analys...
4,Entry-Level Data Analyst,The Federal Savings Bank,"The Federal Savings Bank, a national bank and ...",onsite,NaN,"Chicago, IL","[{'Seniority level': 'Entry level'}, {'Employm...",2022-11-17,https://www.linkedin.com/jobs/view/entry-level...

In [ ]:
jobs_title = jobs['title']
len(jobs_title)

2845

In [ ]:
#for loops
for i in listC:
  print(i)

a
b
c

In [ ]:
#for loops
for i in my_dict.values():
  print(i)
print('\n\n')
for i in my_dict.keys():
  print(i)
print('\n\n')
for key,values in my_dict.items():
  print(f'Key is {key}')
  print(f'Value is {values}')

1
2
3
100
1000
2000



a
b
c
d
e
f



Key is a
Value is 1
Key is b
Value is 2
Key is c
Value is 3
Key is d
Value is 100
Key is e
Value is 1000
Key is f
Value is 2000

In [ ]:
i=0
while i<9:
  print(i)
  i+=1

0
1
2
3
4
5
6
7
8

In [ ]:
#List comprehension
listD = [i**2 for i in range(10)]
listD

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
python = [i for i in 'python']
print(python)
python = [i for i in 'python' if i=='p']
print(python)

['p', 'y', 't', 'h', 'o', 'n']
['p']

In [ ]:
analyst_jobs = [i for i in jobs_title if 'Analyst' in i]
analyst_jobs[0:5]

['Data Analyst - Recent Graduate',
 'Data Analyst - Recent Graduate',
 'Data Analyst',
 'Data Analyst',
 'Entry-Level Data Analyst']

In [ ]:
#exercise
job_roles = [
    {'role': 'Data Analyst', 'skills': ['Python', 'SQL', 'Excel']},
    {'role': 'Data Scientist', 'skills': ['Python', 'R', 'Machine Learning', 'Deep Learning']},
    {'role': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']},
    {'role': 'Data Engineer', 'skills': ['Python', 'Apache Spark', 'Hadoop', 'SQL']},
    {'role': 'Business Intelligence Analyst', 'skills': ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']},
    {'role': 'Quantitative Analyst', 'skills': ['R', 'Python', 'MATLAB', 'Statistics']},
    {'role': 'Operations Analyst', 'skills': ['Python', 'SQL', 'Data Visualization', 'Process Improvement']},
    {'role': 'Database Administrator', 'skills': ['SQL', 'Oracle', 'MySQL', 'Database Management']},
    {'role': 'AI Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']},
    {'role': 'Statistician', 'skills': ['R', 'SAS', 'Python', 'Statistical Modeling']}
]

my_skills = ['Python', 'SQL', 'Excel']
#what job roles i can apply?
qualified_roles = []

for job in job_roles:
  qualified = True
  for skill in my_skills:
    if skill not in job['skills']:
      qualified = False
      break
  if qualified:
    qualified_roles.append(job['role'])

qualified_roles

['Data Analyst', 'Business Intelligence Analyst']

Built-in functions -> like print(), type()...

In [ ]:
#math functions
data_scientist_salaries = [95000, 120000, 105000, 90000, 130000]
print(sum(data_scientist_salaries))
print(max(data_scientist_salaries))
print(min(data_scientist_salaries))
print(sorted(data_scientist_salaries))

540000
130000
90000
[90000, 95000, 105000, 120000, 130000]

In [ ]:
#functions
def cal_salary(base, bonus):
  return base + bonus

cal_salary(10000, 2000)

12000

In [ ]:
# lambda functions
cal_salary2 = lambda base,bonus: base+bonus
cal_salary2(10000, 2000)

12000

In [ ]:
#filter function
a = [1,2,3,4,5,6,7,8,9]
list(filter(lambda x: x%2==0, a))

[2, 4, 6, 8]

In [ ]:
# import statements
import my_module as m
m.a + 5
# if you want particular function from module
from my_module import a #or write * to import all the functions and variables
a + 5

10

In [ ]:
# Statistics module -> Python standard library
from statistics import mean, median, mode
mean(data_scientist_salaries)

108000

In [ ]:
type(jobs['posted_date'][0])

str

In [ ]:
from datetime import datetime
print(datetime.now())
dt = datetime.strptime(jobs['posted_date'][0], '%Y-%m-%d')
print(dt)
print(type(dt))

2024-06-18 08:36:45.434407
2022-11-22 00:00:00
<class 'datetime.datetime'>

In [ ]:
import ast
criteria = jobs['criteria']
criteria0 = ast.literal_eval(criteria[0]) # to change string into collection - list, dict etc
print(type(criteria0))
print(criteria0[0])
criteria0[0]['Seniority level']

<class 'list'>
{'Seniority level': 'Not Applicable'}

'Not Applicable'

**Module** - A file that contains methods and definations <p>**Package** - A collection of modules that perform a specific functionality</p>
**Library** - A library is a collection of packages that provides a multiple functionalities to achieve a single/multiple goals

In [ ]:
import random
random.randint(50000,100000)

50263

In [ ]:
#Generate 1,00,000 numbers of list randomly -
list_n = [random.randint(50000,100000) for _ in range(0,10_00_000)]
# lets compare statistics and numpy methods
import statistics
%timeit statistics.mean(list_n)

297 ms ± 37.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [ ]:
import numpy as np
%timeit numpy.mean(list_n)

36.6 ms ± 744 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [ ]:
# None has a type
type(None)

NoneType

In [ ]:
type(np.nan)

float

In [ ]:
# so if there is np.nan values in dataset, we can use nan mean
np.nanmean(list_n)

74998.725132

In [ ]:
# lets load a dataset from Hugging face
!pip install datasets

Collecting datasets
  Downloading datasets-2.20.0-py3-none-any.whl (547 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 14.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.14.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.25.2)
Collecting pyarrow>=15.0.0 (from datasets)
  Downloading pyarrow-16.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (40.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 14.7 MB/s eta 0:00:00
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.0.3)
Collecting requests>=2.32.2 (from datasets)
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 6.6 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.4)
Collecting xxhash (from datasets)
  Downloading xxhash-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 22.7 MB/s eta 0:00:00
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 14.0 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2024.5.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.23.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.6.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Installing collected packages: xxhash, requests, pyarrow, dill, multiprocess, datasets
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 16.1.0 which is incompatible.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 16.1.0 which is incompatible.
Successfully installed datasets-2.20.0 dill-0.3.8 multiprocess-0.70.16 pyarrow-16.1.0 requests-2.32.3 xxhash-3.4.1

In [ ]:
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading readme:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
        num_rows: 785741
    })
})

In [ ]:
# we want the "train" data
dataset = dataset['train']

In [ ]:
dataset

Dataset({
    features: ['job_title_short', 'job_title', 'job_location', 'job_via', 'job_schedule_type', 'job_work_from_home', 'search_location', 'job_posted_date', 'job_no_degree_mention', 'job_health_insurance', 'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg', 'company_name', 'job_skills', 'job_type_skills'],
    num_rows: 785741
})

In [ ]:
type(dataset)

datasets.arrow_dataset.Dataset

In [ ]:
#we want it to be data frame
df = dataset.to_pandas()
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.head(10) #first 10 rows df.tail() gives last 5 rows

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [ ]:
#see specific columns
df[['job_title_short', 'job_title']].head(10)

        job_title_short                                          job_title
0  Senior Data Engineer  Senior Clinical Data Engineer / Principal Clin...
1          Data Analyst                                       Data Analyst
2         Data Engineer  Data Engineer/Scientist/Analyst, Mid or Senior...
3         Data Engineer  LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...
4         Data Engineer                             Data Engineer- Sr Jobs
5         Data Engineer                                  GCP Data Engineer
6  Senior Data Engineer                  Senior Data Engineer  - GCP Cloud
7         Data Engineer                                      Data Engineer
8      Business Analyst           Technology & Operations Business Analyst
9        Data Scientist                                  Data Scientist II

In [ ]:
# get info about specific row -
df.iloc[0]

job_title_short                                       Senior Data Engineer
job_title                Senior Clinical Data Engineer / Principal Clin...
job_location                                                 Watertown, CT
job_via                                                    via Work Nearby
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                       Texas, United States
job_posted_date                                        2023-06-16 13:44:15
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                          Boehringer Ingelheim
job_skills                                                            None
job_type_skills                                                       None
Name: 0, dtype: object

In [ ]:
#rows
df.loc[0:3]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."

In [ ]:
#specefic columns and rows
df[['job_title_short', 'job_title']].loc[0:3]

        job_title_short                                          job_title
0  Senior Data Engineer  Senior Clinical Data Engineer / Principal Clin...
1          Data Analyst                                       Data Analyst
2         Data Engineer  Data Engineer/Scientist/Analyst, Mid or Senior...
3         Data Engineer  LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('job_title_short').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('job_title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['job_title'].value_counts()
    for x_label, grp in _df_2.groupby('job_title_short')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('job_title_short')
_ = plt.ylabel('job_title')

In [ ]:
print(df.shape)
print(df.size)
print(df.ndim)  #dimension
print(df.columns)
print(df.count())
len(df)

# rather than all the above ones use =
df.info()

(785741, 17)
13357597
2
Index(['job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'company_name', 'job_skills', 'job_type_skills'],
      dtype='object')
job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
#get statistical values of numerical columns
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [ ]:
df.job_country.unique()

array(['United States', 'Mexico', 'Germany', 'Sudan', 'Romania',
       'Denmark', 'Switzerland', 'France', 'Brazil', 'United Kingdom',
       'India', 'Poland', 'Belgium', 'Russia', 'Serbia', 'Singapore',
       'Costa Rica', 'Ireland', 'Italy', 'Malaysia', 'Canada', 'Uruguay',
       'Namibia', 'Estonia', 'Israel', 'Hungary', 'Austria',
       'Philippines', 'Egypt', 'Australia', 'Chile', 'Spain',
       'Netherlands', 'South Africa', 'Colombia', 'Hong Kong', 'Kuwait',
       'Finland', 'Luxembourg', 'China', 'Puerto Rico', 'Sweden',
       'Saudi Arabia', 'Argentina', 'Turkey', 'Panama', 'Nigeria',
       'New Zealand', 'Ukraine', 'Jordan', 'United Arab Emirates',
       'Armenia', 'Pakistan', 'Lesotho', 'Mauritius', 'Portugal',
       'Bahrain', 'Taiwan', "Côte d'Ivoire", 'U.S. Virgin Islands',
       'Réunion', 'Kazakhstan', 'Lithuania', 'Moldova', 'Belarus',
       'Cyprus', 'Bulgaria', 'Honduras', 'Czechia', 'Peru', 'South Korea',
       'Malta', 'Indonesia', 'Tunisia', 'Latvia', 'Slovakia', 'Lebanon',
       'Japan', 'Sri Lanka', 'Slovenia', 'Bangladesh', 'Greece',
       'Ecuador', 'Oman', 'Kenya', 'Guyana', 'Vietnam', 'Norway',
       'Senegal', 'El Salvador', 'Iceland', 'Thailand', 'Ghana',
       'Croatia', 'Myanmar', 'Nepal', 'Morocco', 'Guadeloupe', 'Iraq',
       'Palestine', 'Guinea', 'Albania', 'Guatemala', 'Qatar', 'Uganda',
       'Bolivia', None, 'Dominican Republic', 'Ethiopia', 'Haiti',
       'Uzbekistan', 'Bahamas', 'Liberia', 'Montenegro', 'Cayman Islands',
       'Mongolia', 'Macedonia (FYROM)', 'Azerbaijan', 'Burkina Faso',
       'Guam', 'Trinidad and Tobago', 'Benin', 'Kyrgyzstan',
       'Bosnia and Herzegovina', 'Zambia', 'Cameroon', 'Venezuela',
       'Barbados', 'Togo', 'Rwanda', 'Cambodia', 'Algeria', 'Afghanistan',
       'Congo, Democratic Republic of the', 'Zimbabwe', 'Jamaica',
       'Suriname', 'Mozambique', 'Yemen', 'Tanzania', 'Madagascar',
       'Mali', 'Paraguay', 'Brunei', 'Malawi', 'Nicaragua', 'Libya',
       'Tajikistan', 'Mauritania', 'Botswana', 'Fiji',
       'Northern Mariana Islands', 'Angola', 'Somalia',
       'Papua New Guinea', 'Gambia', 'Djibouti', 'Laos', 'Curaçao',
       'Maldives', 'Bhutan'], dtype=object)

In [ ]:
df.job_country == 'United States'

0          True
1         False
2         False
3          True
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: job_country, Length: 785741, dtype: bool

In [ ]:
#show only jobs with countries in USA with avg. salary > 10000
df[(df.job_country == 'United States') & (df.salary_year_avg > 10_000)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
116,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-10-04 13:04:23,False,False,United States,year,114000.0,NaN,4 Corner Resources,"['r', 'python', 'sql', 't-sql', 'hadoop', 'spa...","{'analyst_tools': ['tableau'], 'libraries': ['..."
146,Data Engineer,Data Engineer Graduate (Real Time Communicatio...,"Seattle, WA",via LinkedIn,Full-time,False,"California, United States",2023-10-21 13:06:16,False,True,United States,year,129500.0,NaN,ByteDance,"['golang', 'scala', 'python', 'java', 'hadoop'...","{'libraries': ['hadoop', 'spark'], 'programmin..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785563,Data Scientist,Data Scientist I/II (Model Risk Management & M...,"Pensacola, FL",via Navy Federal Credit Union - Talentify,Full-time,False,"Florida, United States",2023-01-11 06:22:10,False,False,United States,year,136400.0,NaN,Navy Federal Credit Union,"['r', 'python', 'matplotlib', 'ggplot2', 'spar...","{'analyst_tools': ['word', 'power bi', 'tablea..."
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [ ]:
# where salary avg is not null
df[df.salary_year_avg.notnull()]  #or notna()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",None,None
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [ ]:
# Data cleaning: Lets change the job_posted_date to datetime object from string
import pandas as pd
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
#now we can access date, time, year, dat of week using dt object
df.job_posted_date.dt.month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

In [ ]:
# lets create a new column with job_posted_month
df['job_posted_month'] = df.job_posted_date.dt.month_name()
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,June
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",January
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",October
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",July
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",August

In [ ]:
# sort data
df.sort_values(by='job_posted_date', ascending=False, inplace=True) #inplace means if you want to actually sort the df or not. Default is false which will just show you the sorted df
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,United States,None,NaN,NaN,VirtualVocations,None,None,December
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,None,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",December
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,NaN,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",December
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,None,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",December
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,None,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",December

In [ ]:
# lets drop unecessary columns like salary_hour_avg
df.drop(columns=['salary_hour_avg'], inplace=True)
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,United States,None,NaN,VirtualVocations,None,None,December
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,None,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",December
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",December
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,None,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",December
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,None,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",December

In [ ]:
# to delete rows that have NaN value -
df.dropna(subset=['salary_year_avg'], inplace=True)
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",December
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",December
313161,Data Scientist,Data Scientist - Security Clearance Required,"Newport News, VA",via IT JobServe,Full-time,False,Georgia,2023-12-31 17:31:57,False,False,United States,year,114062.5,Leidos,"['python', 'r', 'sql', 'pandas', 'numpy']","{'libraries': ['pandas', 'numpy'], 'programmin...",December
421728,Data Analyst,Data Analyst - Operations,"Los Angeles, CA",via Indeed,Full-time,False,"California, United States",2023-12-31 16:00:07,False,True,United States,year,72750.0,Wilshire Law Firm Plc,"['sql', 'power bi', 'unity']","{'analyst_tools': ['power bi'], 'other': ['uni...",December
186163,Senior Data Scientist,"Tech Lead / Sr Data Scientist, Product Analyti...","Los Angeles, CA",via LinkedIn,Full-time,False,"California, United States",2023-12-31 15:00:46,False,True,United States,year,271526.5,TikTok,"['sql', 'python', 'r', 'express']","{'programming': ['sql', 'python', 'r'], 'webfr...",December
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108099,Data Scientist,Lead Data Scientist (Hybrid),"Burnsville, MN",via Recruit.net,Full-time,False,"Illinois, United States",2023-01-01 00:21:09,False,False,United States,year,120531.0,Apple Valley,"['java', 'sql', 'sql server', 'spring']","{'databases': ['sql server'], 'libraries': ['s...",January
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01 00:17:58,False,False,United States,year,55000.0,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea...",January
365786,Business Analyst,Hospitality Operations Analyst,Anywhere,via Goodwin Recruiting | Job Board,Full-time,True,Georgia,2023-01-01 00:17:55,False,True,United States,year,90000.0,Goodwin Recruiting,"['sql', 'excel', 'powerpoint', 'outlook']","{'analyst_tools': ['excel', 'powerpoint', 'out...",January
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01 00:06:13,True,False,Argentina,year,65000.0,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",January
108883,Data Scientist,Data Scientist,"Calabasas, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:02:56,False,True,United States,year,110000.0,PlanetArt,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr...",January

In [ ]:
df['salary_year_avg'].min()

15000.0

In [ ]:
#get index value of min
min_salary_index = df['salary_year_avg'].idxmin()
df.loc[min_salary_index]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
job_posted_month                                                  December
Name: 665729, dtype: object

In [ ]:
df['job_title_short'].value_counts()

job_title_short
Data Scientist               5922
Data Analyst                 5451
Data Engineer                4500
Senior Data Scientist        1690
Senior Data Engineer         1591
Senior Data Analyst          1131
Business Analyst              610
Machine Learning Engineer     576
Software Engineer             467
Cloud Engineer                 65
Name: count, dtype: int64

In [ ]:
# get aggregates of different job titles
df.groupby(by='job_title_short')['salary_year_avg'].mean()

job_title_short
Business Analyst              91082.612833
Cloud Engineer               111268.453846
Data Analyst                  93841.907854
Data Engineer                130125.604250
Data Scientist               135988.837171
Machine Learning Engineer    126774.315972
Senior Data Analyst          113911.363665
Senior Data Engineer         145840.611624
Senior Data Scientist        154206.292996
Software Engineer            113393.760054
Name: salary_year_avg, dtype: float64

In [ ]:
# country also
df.groupby(by=['job_title_short','job_country'])['salary_year_avg'].mean()

job_title_short    job_country
Business Analyst   Argentina                71100.000000
                   Australia                87666.666667
                   Bangladesh               16500.000000
                   Belgium                  82620.000000
                   Bulgaria                 73987.500000
                                               ...
Software Engineer  Ukraine                  54000.000000
                   United Arab Emirates     79200.000000
                   United Kingdom          103280.000000
                   United States           137964.929588
                   Vietnam                  53600.000000
Name: salary_year_avg, Length: 598, dtype: float64

In [ ]:
df.groupby(by='job_title_short')['salary_year_avg'].agg(['min', 'max', 'median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0

In [ ]:
# to check whether something exist in a column or not
df['job_country'].isin(['United States', 'India'])

327439    False
336301    False
313161     True
421728     True
186163     True
          ...
108099     True
366073     True
365786     True
334082    False
108883     True
Name: job_country, Length: 22003, dtype: bool

In [ ]:
df['job_country'].isin(['United States', 'India']).any()  #any true value or not

True

Problem : Show aggregation of avg salary of all the jobs in US and ignore the jobs which has no avg salary provided

In [ ]:
us_jobs = df[df['job_country'] == 'United States']
us_jobs.dropna(subset='salary_year_avg', inplace=True)
us_jobs.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'median','count']).sort_values(by='median', ascending=False)

<ipython-input-90-98a4d95ad609>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_jobs.dropna(subset='salary_year_avg', inplace=True)

                               min       max    median  count
job_title_short
Senior Data Scientist      55000.0  475000.0  155000.0   1241
Machine Learning Engineer  44408.5  315000.0  150000.0    128
Senior Data Engineer       45000.0  375000.0  150000.0   1058
Data Scientist             30000.0  960000.0  130000.0   4553
Software Engineer          48982.0  375000.0  130000.0    157
Data Engineer              23496.0  525000.0  125000.0   2915
Cloud Engineer             42000.0  221844.0  116100.0     20
Senior Data Analyst        35360.0  425000.0  110000.0    913
Business Analyst           35000.0  387460.0   90000.0    431
Data Analyst               25000.0  375000.0   90000.0   4350